version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: ../docker/php/Dockerfile
    container_name: docscanner-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - public-data:/var/www/html/public
      - storage-data:/var/www/html/storage
    environment:
      - APP_NAME=Manajemen Dokumen
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=base64:rQJc2pxPwqZOGvsmygNaKkBYCcDICUZ3PRzkAnWO2aQ=
      - APP_URL=https://manajemen.keudisdiksulteng.web.id
      - APP_TIMEZONE=Asia/Makassar
      - DB_CONNECTION=mysql
      - DB_HOST=manajemen-dokumen-docscannerdb-o4evn3
      - DB_PORT=3306
      - DB_DATABASE=docscanner
      - DB_USERNAME=docscanner
      - DB_PASSWORD=wqxxwehyhdlqr7x0
      - SESSION_DRIVER=database
      - CACHE_STORE=database
      - QUEUE_CONNECTION=database
      - LOG_CHANNEL=stderr
    networks:
      - dokploy-network

  nginx:
    image: nginx:alpine
    container_name: docscanner-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - public-data:/var/www/html/public:ro
      - storage-data:/var/www/html/storage:ro
    networks:
      - dokploy-network
    depends_on:
      - app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: https://manajemen.keudisdiksulteng.web.id
    container_name: docscanner-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - dokploy-network

volumes:
  public-data:
  storage-data:

networks:
  dokploy-network:
    external: true
