version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: docscanner-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - APP_NAME=Manajemen Dokumen
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=base64:rQJc2pxPwqZOGvsmygNaKkBYCcDICUZ3PRzkAnWO2aQ=
      - APP_URL=https://manajemen.keudisdiksulteng.web.id
      - APP_TIMEZONE=Asia/Makassar
      - DB_CONNECTION=mysql
      - DB_HOST=manajemen-dokumen-docscannerdb-o4evn3
      - DB_PORT=3306
      - DB_DATABASE=docscanner
      - DB_USERNAME=docscanner
      - DB_PASSWORD=wqxxwehyhdlqr7x0
      - SESSION_DRIVER=database
      - CACHE_STORE=database
      - QUEUE_CONNECTION=database
      - LOG_CHANNEL=stderr
    networks:
      - dokploy-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: https://manajemen.keudisdiksulteng.web.id
    container_name: docscanner-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
