version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: ../docker/php/Dockerfile
    container_name: docscanner-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - public-data:/var/www/html/public
      - storage-data:/var/www/html/storage
    environment:
      - APP_NAME=Manajemen Dokumen
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=base64:rQJc2pxPwqZOGvsmygNaKkBYCcDICUZ3PRzkAnWO2aQ=
      - APP_URL=https://manajemen.keudisdiksulteng.web.id
      - APP_TIMEZONE=Asia/Makassar
      - DB_CONNECTION=mysql
      - DB_HOST=manajemen-dokumen-docscannerdb-o4evn3
      - DB_PORT=3306
      - DB_DATABASE=docscanner
      - DB_USERNAME=docscanner
      - DB_PASSWORD=wqxxwehyhdlp7*0
      - SESSION_DRIVER=database
      - CACHE_STORE=database
      - QUEUE_CONNECTION=database
      - LOG_CHANNEL=stderr
    networks:
      - dokploy-network

  nginx:
    image: nginx:alpine
    container_name: docscanner-nginx
    restart: unless-stopped
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - public-data:/var/www/html/public:ro
      - storage-data:/var/www/html/storage:ro
    networks:
      - dokploy-network
    depends_on:
      - app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.docscanner-api.rule=Host(`manajemen.keudisdiksulteng.web.id`) && (PathPrefix(`/api`) || PathPrefix(`/admin`) || PathPrefix(`/storage`) || PathPrefix(`/sanctum`) || PathPrefix(`/livewire`) || PathPrefix(`/auto-login`) || PathPrefix(`/css`) || PathPrefix(`/js`))"
      - "traefik.http.routers.docscanner-api.entrypoints=websecure"
      - "traefik.http.routers.docscanner-api.tls.certresolver=letsencrypt"
      - "traefik.http.routers.docscanner-api.priority=100"
      - "traefik.http.services.docscanner-api.loadbalancer.server.port=80"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: https://manajemen.keudisdiksulteng.web.id
    container_name: docscanner-frontend
    restart: unless-stopped
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.docscanner-frontend.rule=Host(`manajemen.keudisdiksulteng.web.id`)"
      - "traefik.http.routers.docscanner-frontend.entrypoints=websecure"
      - "traefik.http.routers.docscanner-frontend.tls.certresolver=letsencrypt"
      - "traefik.http.routers.docscanner-frontend.priority=1"
      - "traefik.http.services.docscanner-frontend.loadbalancer.server.port=3000"

volumes:
  public-data:
  storage-data:

networks:
  dokploy-network:
    external: true
